name: Update Wiki

on:
  workflow_dispatch:

env:
  GH_PAT: ${{ secrets.UPDATEWIKITOKEN }}

jobs:
  updatewiki:
    permissions: write-all
    runs-on: "ubuntu-24.04"

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Update Wiki
        continue-on-error: true
        run: |
          php -f make/genmethoddocs.php
          git clone https://$GH_PAT@github.com/horstoeko/zugferd.wiki.git wiki
          mv make/*.md wiki
          cd wiki
          git config user.name "HorstOeko"
          git config user.email "horstoeko@erling.com.de"
          git add .
          git commit -m "Automatische Aktualisierung des Wikis"
          git push
